sudo: required
services:
  - docker

before_install:
  - docker build -t StephenGrider/docker-react -f Dockerfile.dev Dockerfile.dev

script:
  - docker run StephenGrider/docker-react npm run test -- --coverage
  
